# Generated by Django 4.2.4 on 2023-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], max_length=150, verbose_name='Status'),
        ),
    ]
