# Generated by Django 4.2.4 on 2023-09-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_bid_options_alter_itemcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.ForeignKey(default='available', max_length=150, on_delete=django.db.models.deletion.CASCADE, related_name='item_status', to='items.itemstatus'),
        ),
    ]
