# Generated by Django 4.2.4 on 2023-09-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Posted'),
        ),
    ]
