# Generated by Django 4.2.4 on 2023-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
