# Generated by Django 4.2.4 on 2023-09-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservestatus',
            name='status',
            field=models.CharField(choices=[('reserve', 'Reserve'), ('no_reserve', 'No Reserve')], max_length=150, verbose_name='Status'),
        ),
    ]
