# Generated by Django 4.2.4 on 2023-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_reservestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Aold', 'Sold')], max_length=150, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reservestatus',
            name='status',
            field=models.CharField(choices=[('Reserve', 'Reserve'), ('No Reserve', 'No Reserve')], max_length=150, verbose_name='Status'),
        ),
    ]
