# Generated by Django 4.2.4 on 2023-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_itemstatus_status_alter_reservestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatus',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], max_length=150, verbose_name='Status'),
        ),
    ]
