# Generated by Django 4.2.4 on 2023-09-22 04:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_itemstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='item_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_item', to='items.item')),
            ],
            options={
                'verbose_name_plural': 'Item Images',
            },
        ),
    ]
