# Generated by Django 4.2.4 on 2023-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_itemimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover_photo',
            field=models.ImageField(default='no_picture.jpg', upload_to='cover_photos/'),
        ),
    ]
