# Generated by Django 4.2.4 on 2023-09-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', max_length=100, null=True),
        ),
    ]
